### ISSUE TITLE
Duplicate local display

### ISSUE THREAD

**Issue by mix3d** [valnub/pgchat#1]
If you leave the chat, then re-enter, some callback is duplicated, so your local chat display is duplicated the # of times you leave and re-enter.

**Comment by valnub** [comment]
Hi, thanks for reporting. It's totally possible that the chat content needs to be flushed when users re-log. This app is just a simple demo to showcase the chat components of F7 so I don't bother much getting everything 100% right. If you want, feel free to send in a pull request for a fix. Other than that I do not plan to maintain this demo.
